version: "3.9"

services:
  backend:
    build: .
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: dINMlUvcICfUmbKhuMFeBjabuJOYtanm
      MYSQL_HOST: mysql.railway.internal
      MYSQL_PORT: 3306
      MYSQL_DATABASE: railway
    ports:
      - "8001:8000"
    command: uvicorn product.main:app --host 0.0.0.0 --port 8000 --reload
